# Generated by Django 5.1.2 on 2024-10-31 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tiposangre_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.ForeignKey(choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_sangre', to='core.tiposangre', verbose_name='Tipo de Sangre'),
        ),
        migrations.AlterField(
            model_name='tiposangre',
            name='tipo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Tipo de Sangre'),
        ),
    ]
