# Generated by Django 5.1.2 on 2024-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_paciente_tipo_sangre_alter_tiposangre_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposangre',
            name='tipo',
            field=models.CharField(choices=[('A+', 'A Positivo'), ('A-', 'A Negativo'), ('B+', 'B Positivo'), ('B-', 'B Negativo'), ('AB+', 'AB Positivo'), ('AB-', 'AB Negativo'), ('O+', 'O Positivo'), ('O-', 'O Negativo')], max_length=10, unique=True, verbose_name='Tipo de Sangre'),
        ),
    ]
