# Generated by Django 5.1.2 on 2024-11-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_tiposangre_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='tiposangre',
            name='tipo',
            field=models.CharField(max_length=15, unique=True, verbose_name='Tipo de Sangre'),
        ),
    ]
